### ISSUE TITLE
pkgconfig's completionsdir variable

### ISSUE THREAD

**Issue by sagitter** [rpmfusion-infra/rfpkg#1]
Hi,

`bash-completion`'s `pkgconfig` file is not there in the package on EPEL6 (release 1.3.7); this implies a bad recognition of the `completionsdir` variable when we compile `rfpkg` on EPEL6 according to `setup.py` file (https://github.com/rpmfusion-infra/rfpkg/blob/master/setup.py#L11):

```
bashcompdir = None
try:
    import subprocess
    bashcompdir = subprocess.check_output(
        ("pkg-config", "--variable=completionsdir", "bash-completion")).strip()
except:
    pass
if not bashcompdir:
    bashcompdir = "/etc/bash_completion.d"
```

Since `bashcompdir=${prefix}/share/bash-completion/completions` according to `/usr/share/pkgconfig/bash-completion.pc` file of the latest `bash-completion` releases, i think we can just modify [the line #12](https://github.com/rpmfusion-infra/rfpkg/blob/master/setup.py#L12) of [setup.py](https://github.com/rpmfusion-infra/rfpkg/blob/master/setup.py) to resolve this issue:

 `bashcompdir = "/usr/share/bash-completion/completions"`

**Comment by kwizart** [comment]
/usr/share/bash-completion/completions doesn't exists in el6 bash_completion package.
How can would be fixed in fedpkg ?
FYI I plan to disable this bug tracker to use our bugzilla instead.

**Comment by sagitter** [comment]
> /usr/share/bash-completion/completions doesn't exists in el6 bash_completion package.

`fedpkg` installs `fedpkg.bash` in [/etc/bash_completion.d](http://koji.fedoraproject.org/koji/fileinfo?rpmID=6922763&filename=/etc/bash_completion.d/fedpkg.bash) on EPEL6.
But, latest `bash-completion` builds on Fedora provides a `pkgconfig` file like this:

```
prefix=/usr
compatdir=/etc/bash_completion.d
completionsdir=${prefix}/share/bash-completion/completions
helpersdir=${prefix}/share/bash-completion/helpers

Name: bash-completion
Description: programmable completion for the bash shell
URL: http://bash-completion.alioth.debian.org/
Version: 2.1
```

 `completionsdir` points to `/usr/share` in `bash-completion-1.21`, instead it's not defined in `bash-completion-1.3.7` (EPEL6).
Following `bash-completion`'s directives, `rfpkg`'s bash file has different locations.

However, i don't know why, [fedpkg installs fedpkg.bash always under /etc/bash_completion.d](http://koji.fedoraproject.org/koji/fileinfo?rpmID=6922767&filename=/etc/bash_completion.d/fedpkg.bash) (there is no any patch that changes installation of the file), even if `bash-completion-1.2.1`'s .pc file indicates another directory.

**Comment by kwizart** [comment]
This is too much words for a such trivial improvement.
If you can submit an acceptable patch to fedpkg, I will report to rfpg
