### ISSUE TITLE
Switch to SHA512

### ISSUE THREAD

**Issue by kwizart** [rpmfusion-infra/rfpkg#17]
Fedora uses SHA512 for checksum for some time already and the RPM Fusion infra is ready for the same amount of time (nearly).
rfpkg-minimal was only recently updated in rawhide to support that. (thx Leigh).

Let's make the switch in rfpkg
It will make it easier to deal with chromium/chromium-libs-media-freeworld packages and alike.

**Comment by sergiomb2** [comment]
fixed on rfpkg-1.26.2-1
