### ISSUE TITLE
rfpkg mockbuild does'nt use rpmfusion-free/nonfree mock.cfg 

### ISSUE THREAD

**Issue by kwizart** [rpmfusion-infra/rfpkg#26]
When using rfpkg mockbuild in a rpmfusion package, there is a need to parse the section (free/nonfree/cuda/else...) in order to discover which rpmfusion mock configuration to use according to the branch.

Right now, the master branch only points to fedora rawhide.

**Comment by sergiomb2** [comment]
rfpkg mockbuild --root fedora-35-x86_64-rpmfusion_nonfree

I'll study the case , but right now I'm very busy

**Comment by kwizart** [comment]
Sure, thanks (not urgent) but it will ease things a lot.

**Comment by kwizart** [comment]
Fixed in 1.27.3 with 0b583fc682b99dd62f4ef9ea932364e433c11cfc
