### ISSUE TITLE
Anonymous cloning should use https

### ISSUE THREAD

**Issue by tmzullinger** [rpmfusion-infra/rfpkg#6]
As said in a similar, now fixed, [bug report against fedpkg](https://bugzilla.redhat.com/show_bug.cgi?id=1188634):

```
Using git:// does not provide any protection against MITM attackers rewriting the
spec file etc., later resulting in arbitrary code execution in the development
environment.
```

Now that PR #3 is merged, we should consider changing `anongiturl` to `https://pkgs.rpmfusion.org/git/%(module)s` for the same reasons that [fedpkg moved](https://pagure.io/fedpkg/pull-request/147).

I don't know whether any changes to the RPM Fusion koji instance are required or not.  In Fedora there were some changes in the infrastructure and to `rfpkg`/`fedpkg` to allow builds using https.  That requires someone with more knowledge of the RPM Fusion infrastructure to determine (and someone with permissions to create builds to test, of course).  But the basic support should be present in `rpkg` and `rfpkg` now.

Apart from any potential changes to the `koji` config or any build URL override using `construct_build_url` as `fedpkg`, the change would be:

```diff
diff --git i/src/rfpkg.conf w/src/rfpkg.conf
index 221ac39..2ee7aed 100644
--- i/src/rfpkg.conf
+++ w/src/rfpkg.conf
@@ -3,7 +3,7 @@ lookaside = http://pkgs.rpmfusion.org/repo/pkgs
 lookasidehash = md5
 lookaside_cgi = https://pkgs.rpmfusion.org/repo/pkgs/upload.cgi
 gitbaseurl = ssh://%(user)s@pkgs.rpmfusion.org/%(module)s
-anongiturl = git://pkgs.rpmfusion.org/%(module)s
+anongiturl = https://pkgs.rpmfusion.org/git/%(module)s
 branchre = f\d$|f\d\d$|el\d$|master$
 kojiconfig = /etc/koji.conf.d/rpmfusion.conf
 build_client = koji-rpmfusion
```

**Comment by sergiomb2** [comment]
I approve this , @kwizart you also approve it ?

**Comment by tmzullinger** [comment]
I created a branch with the `anongiturl` config change and what I believe is a required change for koji (but should be tested by someone with build access to rpmfusion's koji):

https://github.com/tmzullinger/rfpkg/tree/use-https-for-anongiturl

I can make that a pull request if everyone thinks the move from git:// to https:// makes sense.

**Comment by sergiomb2** [comment]
> I can make that a pull request if everyone thinks the move from git:// to https:// makes sense.

yes, please do the pull request
